### ISSUE TITLE
Play Store not working in all Special builds

### ISSUE THREAD

**Issue by QCSDM8CX** [arnoldthebat/chromiumos#179]
Only shows a notification telling to log out and then log back in

**Comment by mzs112000** [comment]
Play Store/Android apps is a known issue..
It's being worked on right now, but the process takes time...

**Comment by nabilh2020** [comment]
If you got Acer Chromebook C720 C720P - I posted on XDA forum chromebook section a hack to get the Play Store, by modding your Chromium OS R55 using Acer CB recovery rom of R11 - from USB only.

**Comment by arnoldthebat** [comment]
Ref comment
For Android you put in the framework, but all necessary files are missing in
/etc/init
/opt/google/containers/android/
/usr/local/Android_Images/
No wonder Android not working…
I tried to put in the files manually, but it ends up saying no space left.

Missing files & folders in arnoldthebat
/opt/google/containers/android/ – config.json rootfs system.raw.img usr vendor.raw.img
system.raw.img – size: 461983744
vendor.raw.img – size: 48439296
already these two take up all the space left in the rootfs partition…
failed – fix 🤪

**Comment by arnoldthebat** [comment]
Also: https://forum.xda-developers.com/hardware-hacking/chromebooks/chromebook-acer-c720p-getting-google-t3805304/page11

Look to resize sdb3 as part of R70 build

**Comment by nabilh2020** [comment]
The question is: will Google let you implement Android without hassles?
@cloudready said they didn't allow them to, but then they funded them.
Maybe it will be safer to put in F-Droid as alternative to Play Store to cover your base ;)

**Comment by nabilh2020** [comment]
Missing arc files in /etc/init: -

arc-adbd.conf arc-kmsg-logger.conf arc-network.conf arc-removable-media.conf arc-setfattr.conf arc-start-sysctl.conf arc-ureadahead.conf arc-boot-continue.conf  arc-lifetime.conf arc-obb-mounter.conf arc-sdcard.conf arc-setup-env               arc-stop-sysctl.conf arc-ureadahead-trace.conf
arc-camera.conf arc-network-bridge.conf arc-oemcrypto.conf arc-sensor.conf           arc-stale-directory-remover.conf arc-system-mount.conf

Missing folders / files in /opt/google/containers/
android  arc-art  arc-obb-mounter  arc-removable-media  arc-sdcard

**Comment by nabilh2020** [comment]
On a tangent - 
RFC - how did you get Linux menus activated in your v69 release?

**Comment by arnoldthebat** [comment]
They just appeared as part of R69. Nothing for me to do other than build

**Comment by nabilh2020** [comment]
I see... so you are not guilty...
It is Google Chrome OS devs are guilty of crippleware :P

**Comment by nabilh2020** [comment]
Another related query - is it possible to increase the sizes of rootfs A & B partitions without breaking the installation? they seem to be protected, signed?
Also how did you get it so it can boot using Ctrl-U? for chromebooks USB?

**Comment by nabilh2020** [comment]
with arnoldthebat, none.

**Comment by nabilh2020** [comment]
Looking forward to your R70 build - did you get the source code to compile it yet?

**Comment by nabilh2020** [comment]
Just to let you know - 
Installing official Chrome OS on any device (PC / PC-like tablet)
https://forum.xda-developers.com/showpost.php?p=78253693&postcount=110

For Acer Chromebook C720P - from USB 3.0 -
Using chromefy with fizz / caroline yields fully working Chrome OS with arnoldthebat latest r69 Chromium OS as base - 
all works, including Android & crostini, & uses Linux Kernel 4.15
this is the outcome I was looking for!
boots using Control-u

**Comment by nabilh2020** [comment]
Look at post 111 - only for Acer Chromebook C720P - for others you need to identify correct recovery roms to use, for C720P fizz/caroline.

**Comment by erenoglu** [comment]
> Another related query - is it possible to increase the sizes of rootfs A & B partitions without breaking the installation? they seem to be protected, signed?
> Also how did you get it so it can boot using Ctrl-U? for chromebooks USB?

Yes, but you need to remove rootfs protection. Then you can do whatever you want with the rootfs partition (ROOT-A and ROOT-B if you like). I made mine 4GB. 

On Android Apps, is the related container stored in rootfs or somehow extracted at first use to State partition from a heavily compressed image, if the rootfs does not have enough space in normal Chromebooks, I mean, how does Google deal with it?

**Comment by nabilh2020** [comment]
This problem is not an issue for me anymore thanks to the chromefy script - forum.xda-developers.com/showpost.php?p=78253693&postcount=110

**Comment by nabilh2020** [comment]
chromeos_11151.33.0_nocturne_recovery_stable-channel_mp.bin was released, it's for the Google Chromebook Slide & is Chrome OS 71 -

RFC -
 When do you think you will be able to compile Chromium OS r70 or r71?

**Comment by nabilh2020** [comment]
Testing chromeos_11151.33.0_nocturne_recovery_stable-channel_mp.bin
on Acer Chromebook C720P -
https://forum.xda-developers.com/showpost.php?p=78338599&postcount=118

**Comment by nabilh2020** [comment]
New Chromebook recovery release in recovery.conf - chromeos_11021.81.0

Might be r70 ? - will @arnoldthebat builds get compiled soon?

https://forum.xda-developers.com/showpost.php?p=78370123&postcount=121

**Comment by arnoldthebat** [comment]
For ref, Ive started building rootfs with 4GB for all builds. Hopefully this will stop you having to resize stuff

**Comment by arnoldthebat** [comment]
@nabilh2020 it will be R71. Just testing now and will wait for the final stable from Google, then I can release...

**Comment by nabilh2020** [comment]
Can you also please release R70 ;)

**Comment by erenoglu** [comment]
Hi @arnoldthebat, could you please also include the tpm-emulator package in your build from chromiumos sources or at least in a test image? I'd like to fiddle with it to see if we could have tpm functions working. (eap tls, certificate import and bind, etc)

**Comment by nabilh2020** [comment]
> @nabilh2020 You don't need R70 Chromium to use R70 ChromeOS, you are able to jump from 69 to 70 or 71. You might as well wait for 71 as that will be easier on Arnold

My most successful result is with special build R55 using the original Kernel 3.18 of cyan R69 google OS recovery rom as per my thread - https://forum.xda-developers.com/hardware-hacking/chromebooks/chromebook-acer-c720p-getting-google-t3805304

**Comment by imperador** [comment]
> For ref, Ive started building rootfs with 4GB for all builds. Hopefully this will stop you having to resize stuff

Thanks a lot for this. It will make our process so much easier

**Comment by nabilh2020** [comment]
Arnold, no need to build release 70 - I got FydeOS which is R70 - & it works a treat to install Chrome OS r70 on Acer Chromebook C720P.

**Comment by sojab0on** [comment]
Shure hope this will be sorted for the special builds i coudnt get de normal builds to boot up on my dell latitude E6220.

Will use it without the play store until Arnold gets it fixed for all images and rolls out the R71 or R72 image for specials so i can use the update feature.

Keep up the good work Arnold.

**Comment by nabilh2020** [comment]
Still no Android support with your R72 special build release,
ROOT-A is also still 2GB not 4GB you promised...
by using chromefy with new TPM 2.0 hack, 
one can get Android Pie (9) with Nocturne on Acer Iconia W700...
finally, no graphics drivers for Acer Chromebook C720P... so not useful...
https://forum.xda-developers.com/showpost.php?p=78688278&postcount=133

**Comment by TCU14** [comment]
@nabilh2020 just because these builds aren't useful for you does not mean they aren't useful to somebody elsewhere. Also, it could be he hasn't figured out the 4GB thing yet and is working on it.. 
Finally, you could build your own kernel from the source for that Acer if you want to try. Otherwise, just be patient. Don't post something that screams entitlement

**Comment by mattschwantes** [comment]
Thanks @arnoldthebat .  Your efforts are appreciated by a lot of people who are lurking quietly.

@nabilh2020 Thanks for your posts on github and XDA. I'm working on the Asus Chromebit CS10 missing Play Store.

**Comment by nabilh2020** [comment]
It's OK - I am bipolar :)
Look into FydeOS 5.1/5.2 they got their ROOT-A 2.66GB
I am not patient, sadly...
thanks for your works!
Any suggestion about the graphics for Acer Chromebook C720P, it's broken in R72 :(

**Comment by nabilh2020** [comment]
> @nabilh2020 just because these builds aren't useful for you does not mean they aren't useful to somebody elsewhere. Also, it could be he hasn't figured out the 4GB thing yet and is working on it..
> Finally, you could build your own kernel from the source for that Acer if you want to try. Otherwise, just be patient. Don't post something that screams entitlement

Actually I am more interested in getting it to work with Acer Chromebook C720P than any other Laptop, that was the purpose of my last threads in XDA Developers Forum.

Greets & ACK's ;)

**Comment by nabilh2020** [comment]
> Asus Chromebit CS10

My Asus Chromebit CS10 is gathering dust - I have not used it in a long while - 
I am using BBEN ICS clone instead with my hacked cyan/ABAT R55 combination - very performant & rock solid stable with Android 7.1.1 & crouton ubuntu bionic xfce4.

**Comment by nabilh2020** [comment]
> > @nabilh2020 just because these builds aren't useful for you does not mean they aren't useful to somebody elsewhere. Also, it could be he hasn't figured out the 4GB thing yet and is working on it..
> > Finally, you could build your own kernel from the source for that Acer if you want to try. Otherwise, just be patient. Don't post something that screams entitlement
> 
> Actually I am more interested in getting it to work with Acer Chromebook C720P than any other Laptop, that was the purpose of my last threads in XDA Developers Forum.
> 
> Greets & ACK's ;)

On Acer Chromebook C720P I am pleased to report that using FydeOS 5.3 (r70) as base image, I now have a fully functioning Google Chrome OS using chromefy with Nocturne, powerwashing, then overwriting it using chromefy1 with eve/caroline, it seems everything works, Android, camera, camera migration, crostini - so to answer my XDA C720P threads, this is solved - of course there will soon be cyan R71 which could yield same results with chromefy1 cyan r71 / caroline r71...

**Comment by nabilh2020** [comment]
Since you do not seem interested to build Chromium OS release 71 - can you point me to how to do it, or at least how to compile kernel for r71 so I can add drivers I need for Acer CB C720P?
or you like to hoard know-how instead of share?

**Comment by nabilh2020** [comment]
I managed to download the source code for Chrome OS r72 - almost ready to build - results, or failures here: 
https://forum.xda-developers.com/showpost.php?p=78830818&postcount=3

**Comment by arnoldthebat** [comment]
@imperador Try this build for the 4GB rootfs partitions. I will look to maintain it sperately from the main builds if it helps you out.

**Comment by imperador** [comment]
@arnoldthebat Thanks a lot! I'll try it tomorrow

**Comment by nabilh2020** [comment]
Managed to build Chrome OS Kernel with extra modules & install it manually - 
Linux localhost 4.14.96-09859-ga5c3f2f0428a-dirty #1 SMP PREEMPT Wed Feb 13 08:04:55 GMT 2019 x86_64 Intel(R) Core(TM) i3-2365M CPU @ 1.40GHz GenuineIntel GNU/Linux
details upstream of here -
https://forum.xda-developers.com/showpost.php?p=78895755&postcount=7
it did not solve the booting issue for Acer Chromebook C720P

**Comment by nabilh2020** [comment]
I guess am on my own & will have to figure out the hard way how to build up a Chromium OS for myself, sad to see coders hoarding knowledge :(

**Comment by Red5d** [comment]
Nobody's "hoarding" knowledge. The full developer guide for building Chromium OS images, installing it, developing it, etc is publicly available from Google here: https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md

**Comment by nabilh2020** [comment]
> Nobody's "hoarding" knowledge. The full developer guide for building Chromium OS images, installing it, developing it, etc is publicly available from Google here: [chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md](https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md)

Well I am not a great coder, I managed to figure out how to build the kernel, & manually force it in, but it's far from perfect - asking for advice is not a sin.

I have no problem with Ubuntu or Arch Linux kernel building, but Google is not making clear instructions for obvious reasons - corporate greed.

**Comment by nabilh2020** [comment]
OK - I finally got the chromefied ATB v72 with eve 73 / swtpm kernel upgraded from 4.14.83 to 4.14.96 - it works great on Acer iconia W700 including Android, camera & camera migration - the oddity - it removed crostini - it I put back kernel 4.14.83 crostini comes back - is there a setting I am missing? appreciate an answer if any - 
details here -
https://forum.xda-developers.com/showpost.php?p=78915157&postcount=8

**Comment by arnoldthebat** [comment]
> OK - I finally got the chromefied ATB v72 with eve 73 / swtpm kernel upgraded from 4.14.83 to 4.14.96 - it works great on Acer iconia W700 including Android, camera & camera migration - the oddity - it removed crostini - it I put back kernel 4.14.83 crostini comes back - is there a setting I am missing? appreciate an answer if any -
> details here -
> https://forum.xda-developers.com/showpost.php?p=78915157&postcount=8

If you share the .config Ill build it into my next release...

**Comment by nabilh2020** [comment]
> If you share the .config Ill build it into my next release...

sure - I need to recheck it as when I run make it tends to remove some settings like the one for backlight for apple macbook air

I will put it in dropbox & post the link

**Comment by nabilh2020** [comment]
Here is the dropbox link
https://www.dropbox.com/s/esr407ybr5tev1u/configs.zip?dl=0
it has the FydeOS 5.3.1 base config I extracted & your ATB v72 which I merged Fydeos 5.3.1 entries into - it updates to 4.14.96 from your 4.14.83 (replace z.config by .config)
It does compile a kernel OK - I did this manually, still learning how to do it signed. As I said details in my XDA thread.
I added all LCD panels modules, maybe it will finally allow to boot Chromebook C720P to GUI.
Oddly, I lose crostini, maybe unsigned kernels do that.

**Comment by nabilh2020** [comment]
Still no luck with Acer Chromebook C720P - tried several changes to .config with make menuconfig & manually - boots to a blank screen still :(
Fydeos 5.3.1 does not have this problem.
Also tried just the .config of FydeOS on its own, & strangely no luck - there must be something else.

**Comment by nabilh2020** [comment]
I need help - 

after building / updating kernel from 4.14.83 to 4.14.96 - 

Just building the kernel & forcing in vmlinuz.A in /dev/sdx12 syslinux using bzImage (& modules in /lib/modules)
is apparently not enough...

It seems I also need to generate a new blob for the kernel which is /dev/sdx2

 https://forum.xda-developers.com/showpost.php?p=78945492&postcount=13

this might be the cause for losing crostini...

**Comment by nabilh2020** [comment]
RFC - how to produce a Chromium OS blob for loading an updated newer kernel? @googledevs @arnoldthebat @itsfoss2 @CroissantDev @meNabster
https://forum.xda-developers.com/showpost.php?p=78959880&postcount=18

**Comment by nabilh2020** [comment]
Can you provide your kernel.bin to flash to /dev/sdb2?

**Comment by nabilh2020** [comment]
Anyways, I am following up on a thorough analysis of blobs in that thread, will welcome any suggestions on how to generate data for config.txt to build a successful blob using:
vbutil_kernel --pack new_kern67.bin \
--keyblock /usr/share/vboot/devkeys/kernel.keyblock \
--signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \
--version 1 \
--config config.txt \
--bootloader /lib64/bootstub/bootstub.efi \
--vmlinuz vmlinuz-4.14.67

**Comment by nabilh2020** [comment]
Your latest 0Day 10/03 R72 release still does not boot to GUI Acer Chromebook C720P - what changed from R69 to R72 (or for that matter from R55 to R58) ?
In R55 I have to use Ctrl-L
In R69 I have to use Ctrl-U
./.

**Comment by nabilh2020** [comment]
RFC - why did you change the size of the blob partitions KERN-A/KERN-B from 16MB ib R69 to 64MB in R72? - FydeOS 6.0 kept them at16MB...

**Comment by arnoldthebat** [comment]
I didn't consciously. The default build scripts made the change...

**Comment by nabilh2020** [comment]
Looks like chromium devs cripple software not to interfere with Google profits - 
I am soon going to upgrade my Chromebook firmware to make it like a normal PC - so I won't have to look for hacks which are harder to get by with Google closing loopholes...
It will be interesting to find out how ctrl-u vs ctrl-l get activated. as I said
R55 works with ctrl-l only
R69 works with ctrl-u only

**Comment by nabilh2020** [comment]
I can confirm that it is Google Devs who increased Chromium/Chrome OS KERN-A/KERN-B P2/P4 from 16MB to 64MB.

**Comment by mzs112000** [comment]
> I can confirm that it is Google Devs who increased Chromium/Chrome OS KERN-A/KERN-B P2/P4 from 16MB to 64MB.

I am going to take a wild guess here and say that Google probably increased KERN-A/KERN-B to 64MB in order to future-proof the OS.
16MB is getting kinda small for a Linux kernel image.
Linux kernel is getting bigger each release, and Google adds their own patches to it for Android, and ChromeOS.
Having a larger kernel partition allows Google to add more modules in, which they need in order to support all of the Chromeboooks on the market.

**Comment by nabilh2020** [comment]
Pleased to let you know that booting ATB Special v72 is solved by flashing the firmware of Acer Chromebook C720P...
details here - 
https://mrchromebox.tech/#fwscript
https://forum.xda-developers.com/showpost.php?p=79259192&postcount=185
https://forum.xda-developers.com/hardware-hacking/chromebooks/using-chromeos-firmware-utility-script-t3917229/post79243697#post79243697

**Comment by rsdkz** [comment]
Latest special build for 64-bit systems has Play Store in it, does not work though, it says that "a problem happened". After Chromefy-ing ChromiumOS it works.

**Comment by nabilh2020** [comment]
> Latest special build for 64-bit systems has Play Store in it, does not work though, it says that "a problem happened". After Chromefy-ing ChromiumOS it works.

After flashing firmware I can boot ATB v72 - 
I am using cyan v72 on ATB v72 with my hack method using original ROOT-A partition & original 3.18 cyan kernel, it works for Acer CB C720P with crostini, camera, & Android 7.1.1

**Comment by naimoe902** [comment]
> > > @nabilh2020 just because these builds aren't useful for you does not mean they aren't useful to somebody elsewhere. Also, it could be he hasn't figured out the 4GB thing yet and is working on it..
> > > Finally, you could build your own kernel from the source for that Acer if you want to try. Otherwise, just be patient. Don't post something that screams entitlement
> > 
> > 
> > Actually I am more interested in getting it to work with Acer Chromebook C720P than any other Laptop, that was the purpose of my last threads in XDA Developers Forum.
> > Greets & ACK's ;)
> 
> On Acer Chromebook C720P I am pleased to report that using FydeOS 5.3 (r70) as base image, I now have a fully functioning Google Chrome OS using chromefy with Nocturne, powerwashing, then overwriting it using chromefy1 with eve/caroline, it seems everything works, Android, camera, camera migration, crostini - so to answer my XDA C720P threads, this is solved - of course there will soon be cyan R71 which could yield same results with chromefy1 cyan r71 / caroline r71...
> Instructions here - https://forum.xda-developers.com/showpost.php?p=78737282&postcount=143

you still have the fyde os 5.3 image? If possibile can you send it to me thks.

**Comment by nabilh2020** [comment]
naimoe902
FydeOS 5.3.1 image - where to upload it? - I have not enough space in my accounts...

**Comment by naimoe902** [comment]
Thanks for your reply. Can you upload it to Drive or Mega? And I want to
ask you. I just found v5.2 dev image. Have you tried that version? Any
issues so far? I am using that image and everything looks good .

**Comment by naimoe902** [comment]
> naimoe902
> FydeOS 5.3.1 image - where to upload it? - I have not enough space in my accounts...

Thanks for your reply. Can you upload it to Drive or Mega? And I want to
ask you. I just found v5.2 dev image. Have you tried that version? Any
issues so far? I am using that image and everything looks good .

**Comment by arnoldthebat** [comment]
Im closing this since its not relevant now. I cannot fix the Play Store until Google open source the blobs. There are well documented ways around this using Google searches
